name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cppcheck valgrind
    
    - name: Build main binary
      run: make
        
    - name: Build tests
      run: make test_runner
      
    - name: Run unit tests
      run: make test
      
    - name: Static Analysis (cppcheck)
      run: make lint
      
    - name: Memory check on tests
      run: make memcheck-test
      
    - name: Test basic functionality
      run: timeout 10s ./netscan -h 127.0.0.1 -p 22 -t 2 || true

  build-packages:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential rpm devscripts debhelper
    
    - name: Build binary
      run: make
        
    - name: Create packages directory
      run: mkdir -p packages
        
    - name: Create DEB package
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        mkdir -p netscan_${VERSION}/DEBIAN
        mkdir -p netscan_${VERSION}/usr/bin
        cp netscan netscan_${VERSION}/usr/bin/
        cat > netscan_${VERSION}/DEBIAN/control << EOF
        Package: netscan
        Version: ${VERSION}
        Architecture: amd64
        Maintainer: User <user@example.com>
        Description: Network port scanner
        EOF
        dpkg-deb --build netscan_${VERSION} packages/

    - name: Create RPM package
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        
        # Create spec file
        cat > ~/rpmbuild/SPECS/netscan.spec << EOF
        Name:           netscan
        Version:        ${VERSION}
        Release:        1%{?dist}
        Summary:        Network port scanner
        License:        MIT
        BuildArch:      x86_64
        
        %description
        Simple network port scanner tool
        
        %prep
        
        %build
        
        %install
        mkdir -p %{buildroot}%{_bindir}
        cp %{_sourcedir}/netscan %{buildroot}%{_bindir}/
        
        %files
        %{_bindir}/netscan
        
        %changelog
        * $(date +'%a %b %d %Y') User <user@example.com> - ${VERSION}-1
        - Release ${VERSION}
        EOF
        
        # Copy binary to SOURCES
        cp netscan ~/rpmbuild/SOURCES/
        
        # Build RPM
        rpmbuild -bb ~/rpmbuild/SPECS/netscan.spec
        
        # Copy to packages directory
        cp ~/rpmbuild/RPMS/x86_64/*.rpm packages/
        
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: packages/*

  release:
    needs: build-packages
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: packages/*
        generate_release_notes: true